# Generated by Django 2.1.3 on 2018-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IT_assets_pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pc_Type', models.CharField(max_length=32, null=True, verbose_name='类型')),
                ('Device_ID_Pc', models.CharField(max_length=32, null=True, verbose_name='设备编号')),
                ('Base_Pc', models.CharField(max_length=32, null=True, verbose_name='设别存放地')),
                ('Date_of_Purchase', models.DateTimeField(verbose_name='购买时间')),
                ('Value_Pc', models.CharField(max_length=12, null=True, verbose_name='原值')),
                ('Brand_Pc', models.CharField(default='Dell', max_length=32, verbose_name='品牌')),
                ('model_Pc', models.CharField(default='E7470', max_length=32, verbose_name='型号')),
                ('Service_Tag', models.CharField(max_length=32, null=True, verbose_name='服务编号')),
                ('Equipment_Status_Pc', models.CharField(max_length=32, null=True, verbose_name='设备状态')),
                ('User_Name_Pc', models.CharField(max_length=32, null=True, verbose_name='中文姓名')),
                ('User_Name_Pc_1', models.CharField(max_length=24, null=True, verbose_name='英文名')),
                ('User_Id', models.CharField(max_length=12, null=True, verbose_name='员工号')),
            ],
        ),
    ]
