# Generated by Django 2.1.3 on 2018-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_zichan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_assets_pc',
            name='Base_Pc',
            field=models.CharField(default='shanghai', max_length=32, null=True, verbose_name='设别存放地'),
        ),
    ]
