# Generated by Django 2.1.3 on 2018-12-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_zichan', '0004_auto_20181203_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect_employee_information_PC',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_Englishname', models.CharField(blank=True, max_length=32, null=True, verbose_name='英文名')),
                ('User_Chinesename', models.CharField(blank=True, max_length=32, null=True, verbose_name='中文名')),
                ('Product_Name', models.CharField(blank=True, default='Desktop', max_length=32, null=True, verbose_name='产品名称')),
                ('Amount', models.CharField(blank=True, default='1', max_length=32, null=True, verbose_name='数量')),
                ('Attribution_Dept', models.CharField(blank=True, max_length=32, null=True, verbose_name='归属部门')),
                ('Number_Pc', models.CharField(blank=True, max_length=32, null=True, verbose_name='机器编号')),
                ('Brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='品牌')),
                ('xinghao', models.CharField(blank=True, default='Latitude 7470', max_length=32, null=True, verbose_name='型号')),
                ('Service_Tag', models.CharField(max_length=32, verbose_name='服务编号')),
                ('E_Service', models.CharField(max_length=32, verbose_name='快速服务代码')),
            ],
        ),
    ]
