# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-06 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT_zichan', '0006_auto_20190506_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphone',
            options={'verbose_name': '手机领用库存表', 'verbose_name_plural': '手机领用库存表'},
        ),
    ]
